### ISSUE TITLE
Question: Team stats/rankings availability

### ISSUE THREAD

**Issue by minter** [Zmalski/NHL-API-Reference#1]
Thank you so much for this documentation!

I was wondering if you'd discovered a way to fetch **TEAM** stats for a season, and their ranks. Such as:

SHOTS PER GAME
1. Carolina (35.3)
2. Toronto (34.9)
3. Nashville (33.5)

_(etc)_

The previous API provided them through a call of https://statsapi.web.nhl.com/api/v1/teams/12/stats?stats=statsSingleSeason&season=20232024, but I didn't see a way to get team stats in your docs.

I'm converting a tool from the old to the new API, and this is really the last thing I'm missing - to fetch the team stats for my team, and display the league ranking for those stats.

Example output from my tool:

```
Season stats and NHL ranks for the Carolina Hurricanes (1/3)

Average Goals Scored: 3.2 (Rank: 16th)
Average Goals Allowed: 3.2 (Rank: 17th)
Power Play Percentage: 24.6 (Rank: 7th)
```

**Comment by Zmalski** [comment]
I think https://github.com/Zmalski/NHL-API-Reference#get-team-stats is the most likely endpoint that you'll find the team stats that you're looking for. Although, that endpoint is still partially a mystery. Hopefully that's helpful and points you roughly in the right direction. I'll poke around that endpoint over the next couple days and update if I find anything that might help.

**Comment by Zmalski** [comment]
Alright well it took a lot less than a couple days:

To fetch team stats for a season and sort them by a certain field (e.g. shots per game):
`https://api.nhle.com/stats/rest/en/team/summary?sort=shotsForPerGame&cayenneExp=seasonId=20232024%20and%20gameTypeId=2`

This example URL will fetch team stats for the regular season games of the 2023-2024 season and sort them by shots **for** per game.
The parameters:
- `sort`: Field to sort results by
- `cayenneExp` Basically an SQL query via an ORM for whatever DB they're using on the backend. In this case we're filtering for the current season (`seasonId=20232024`) and by regular season games (I think) (`gameTypeId=2`).

This returns a list of objects, each one mapping to a team and containing team stats. This list will be sorted by whichever field you provided in the `sort` parameter. Here's an example of a list item that would be returned:

```
      {
         "faceoffWinPct" : 0.549733,
         "gamesPlayed" : 19,
         "goalsAgainst" : 50,
         "goalsAgainstPerGame" : 2.63157,
         "goalsFor" : 60,
         "goalsForPerGame" : 3.15789,
         "losses" : 10,
         "otLosses" : 0,
         "penaltyKillNetPct" : 0.866666,
         "penaltyKillPct" : 0.85,
         "pointPct" : 0.47368,
         "points" : 18,
         "powerPlayNetPct" : 0.075471,
         "powerPlayPct" : 0.132075,
         "regulationAndOtWins" : 9,
         "seasonId" : 20232024,
         "shotsAgainstPerGame" : 31.05263,
         "shotsForPerGame" : 33.8421,
         "teamFullName" : "Pittsburgh Penguins",
         "teamId" : 5,
         "ties" : null,
         "wins" : 9,
         "winsInRegulation" : 8,
         "winsInShootout" : 0
      } 
```

Hope that helps!

**Comment by minter** [comment]
That worked great! Thank you so much!
