### ISSUE TITLE
Highlight/Recap ID mappings

### ISSUE THREAD

**Issue by minter** [Zmalski/NHL-API-Reference#11]
Within the game landing page, there are numeric IDs for things like goal highlights, game recaps, and condensed games. Do you know how to turn those into URLs to view the actual content?

```
        "goals": [
          {
            "situationCode": "1551",
            "strength": "ev",
            "playerId": 8477960,
            "firstName": {
              "default": "Adrian"
            },
            "lastName": {
              "default": "Kempe"
            },
            "name": {
              "default": "A. Kempe"
            },
            "teamAbbrev": {
              "default": "LAK"
            },
            "headshot": "https://assets.nhle.com/mugs/nhl/20232024/LAK/8477960.png",
            "highlightClip": 6345776353112,
            "highlightClipFr": 6345777136112,
```

```    },
    "gameVideo": {
      "threeMinRecap": 6345743026112,
      "condensedGame": 6345743402112
    }
```

**Comment by Zmalski** [comment]
I was able to find (what I believe to be) the actual URL structure for what the condensed games looks like. Here's an example:

`https://www.nhl.com/video/condensed-game-kings-at-blues-1-28-24-6345782742112`

Wasn't able to see anything obvious for the other categories, but they might be similar.  Hope that helps for now.

**Comment by Zmalski** [comment]
Actually, it looks like highlights are similar, but it might be tough to determine what the URLs are programmatically:

`https://www.nhl.com/video/topic/highlights/lak-stl-danault-scores-goal-against-joel-hofer-6345781435112`

**Comment by minter** [comment]
Rats - I was hoping there was a URL link somewhere in the API. I appreciate you checking!
