### ISSUE TITLE
Access to video recap

### ISSUE THREAD

**Issue by tylergrimm12** [Zmalski/NHL-API-Reference#14]
Within the the daily scores (https://api-web.nhle.com/v1/score/now) there is a three minutes recap video for each game. Any idea on how I could get access to that video?

**Comment by nelgin** [comment]
https://www.nhl.com/video/recap-panthers-at-red-wings-3-2-24-6348106021112

Something like that.

You're going to have problems downloading it though but you can link to it.

**Comment by Zmalski** [comment]
Not sure I totally follow. I'll try my best to answer.

In this example entry:

`threeMinRecap:  "/video/recap-panthers-at-rangers-3-4-24-6348243525112"`

You would access the three minute recap by just putting that string at the end of "https://www.nhl.com"

So: "https://www.nhl.com/video/recap-panthers-at-rangers-3-4-24-6348243525112"
