### ISSUE TITLE
Hey..... its playoff time baby !

### ISSUE THREAD

**Issue by riffnshred** [Zmalski/NHL-API-Reference#19]
Series carousel
https://api-web.nhle.com/v1/playoff-series/carousel/20232024/

Schedule for each series
https://api-web.nhle.com/v1/schedule/playoff-series/20232024/a/
https://api-web.nhle.com/v1/schedule/playoff-series/20232024/b/
https://api-web.nhle.com/v1/schedule/playoff-series/20232024/c/
https://api-web.nhle.com/v1/schedule/playoff-series/20232024/d/

Playoff Bracket !
https://api-web.nhle.com/v1/playoff-bracket/2024

**Comment by Zmalski** [comment]
Great find! Will get this added ASAP.

**Comment by riffnshred** [comment]
All good. I'll add what I find in the same comment. The Bracket one is now live

**Comment by Zmalski** [comment]
Added endpoints to doc
