### ISSUE TITLE
Get player id from player name

### ISSUE THREAD

**Issue by scottstubberfield** [Zmalski/NHL-API-Reference#21]
Has anyone been able to get a player's id from just their name? I haven't finished it yet but the only way I seem to be able think this will work is look up the player's team, grab the roster and then loop through all the players until I find them. Is there another API available that makes this easier?

**Comment by dsaladbar617** [comment]
That's the best way using this api I believe. That's how the old nhl website used to handle it. They do have a different api that is used on the player search input on the players page I believe, that suggests names based off of what is typed in that will also return the corresponding id. I think it is not allowed from all sources though so it won't work once deployed.

**Comment by scottstubberfield** [comment]
Thanks Daniel
