### ISSUE TITLE
Who owns the API that is documented here?

### ISSUE THREAD

**Issue by rpungin** [Zmalski/NHL-API-Reference#26]
Hi,

Can someone tell me who owns and maintains this API? Is it the NHL itself? Where can we find the *official* documentation on it? What is the terms of use and service level agreement for it?

**Comment by Zmalski** [comment]
It's a safe assumption that the NHL owns the endpoints since they are on official NHL domains.

There is no official documentation, creating the need for documentation such as this.

There are no published terms of use, as far as I'm aware. Try not to abuse it.

Hope this helps.

**Comment by Healer928802** [comment]
@Zmalski , hey! 
What do you mean "Try not to abuse it"?

Thank you!

**Comment by Zmalski** [comment]
Essentially just treat it with respect (e.g. don't barrage endpoints with a huge volume of requests).
