### ISSUE TITLE
Draft Tracker Info - NHL App

### ISSUE THREAD

**Issue by coflaherty-DTB** [Zmalski/NHL-API-Reference#29]
NHL app has added a draft tracker tab to their tab bar. Does anyone know where on the NHL website this tab points to for this information?

**Comment by dsaladbar617** [comment]
I would love to find this out as well. I believe that we're able to see the current years draft, but I can't for the life of me figure out how to specify which year to request.

**Comment by coflaherty-DTB** [comment]
Looks like they just added it to the website:
https://www.nhl.com/draft/tracker

API call:
https://api-web.nhle.com/v1/draft/picks/2024/1

**Comment by dsaladbar617** [comment]
The number after the year seems to correspond with the draft round. I wonder if there is a way to see all picks.

**Comment by dsaladbar617** [comment]
nevermind figured it out. If you replace 1 with all I believe you get all of the picks for that year.

**Comment by coflaherty-DTB** [comment]
Oh wow nice find, thanks for that!
