### ISSUE TITLE
Schedule by season

### ISSUE THREAD

**Issue by alexandramastrangelo** [Zmalski/NHL-API-Reference#3]
Thank you so much for providing this documentation, you have been a life saver

Is there any way to access all of the games in a season? I know it is possible to get team schedules by season, or schedule by month, but I cannot seem to find schedule (or games) by season

**Comment by Zmalski** [comment]
https://api.nhle.com/stats/rest/en/game retrieves what appears to be every NHL game played. It also looks like it includes the current season's scheduled games.

I'd imagine there's probably parameters you could pass to trim the results a bit. I'll let you know if I uncover anything.

Hopefully that helps!

**Comment by tristmist** [comment]
Do you know if there is any NHL api that tells you who was on ice for each goal for and against in a game? I know the HTML reports will tell you who was on ice for every goal scored but I haven't been able to find it for the API. Is it possible it exists in the API?

**Comment by mtutsock** [comment]
In case anyone comes across this issue or is still looking for a solution, you can do the following to get the schedule by season:

`https://api.nhle.com/stats/rest/en/game?cayenneExp=season=20232024`

It doesn't give you as much information about the games as the old schedule API did, but at least you don't have to iterate through a bunch of dates, weeks, months, teams, etc. to get the full schedule.
