### ISSUE TITLE
nhl rest api gone? down?

### ISSUE THREAD

**Issue by alanryder** [Zmalski/NHL-API-Reference#31]
Calls to the nhl's rest api [api.nhle.com/stats/rest/...] are going unanswered as of 10am today.  This was OK at 9am.  Calls to the web api [api-web.nhle.com/...] and records api [records.nhl.com/site/api/] are working.

**Comment by Afischbacher** [comment]
Looks like it is back online @alanryder. They may have been doing server maintenance🤷
