### ISSUE TITLE
Player Stats - Faceoffs and other Extended stats no longer available under the Player API

### ISSUE THREAD

**Issue by MunAli-Man** [Zmalski/NHL-API-Reference#37]
Hi - Im recently, restarting my NHL API, and i noticed that my API load was failing because several extended stats like Faceoffs, short handed goals, TOI are all gone.  Did these move to a new API or are fully gone?>

**Comment by andrewderango** [comment]
You can find these stats using specific stat queries. Unfortunately the response doesn't contain the player ID's, but it includes their full name, team, and position so you should be able to successfully join it based on these fields.

Faceoffs: [FaceoffPercentages](https://api.nhle.com/stats/rest/en/skater/faceoffpercentages?isAggregate=false&isGame=false&sort=%5B%7B%22property%22:%22totalFaceoffs%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22playerId%22,%22direction%22:%22ASC%22%7D%5D&start=0&limit=9999&cayenneExp=gameTypeId=2%20and%20seasonId%3C=20232024%20and%20seasonId%3E=20232024) and [FaceoffWins](https://api.nhle.com/stats/rest/en/skater/faceoffwins?isAggregate=false&isGame=false&sort=%5B%7B%22property%22:%22totalFaceoffWins%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22faceoffWinPct%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22playerId%22,%22direction%22:%22ASC%22%7D%5D&start=0&limit=9999&cayenneExp=gameTypeId=2%20and%20seasonId%3C=20232024%20and%20seasonId%3E=20232024)
SH Goals and TOI: [Summary](https://api.nhle.com/stats/rest/en/skater/summary?isAggregate=false&isGame=false&sort=%5B%7B%22property%22:%22points%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22goals%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22assists%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22playerId%22,%22direction%22:%22ASC%22%7D%5D&start=0&limit=9999&cayenneExp=gameTypeId=2%20and%20seasonId%3C=20232024%20and%20seasonId%3E=20232024)

Of course feel free to modify the parameters for your use case. If you need more extended options there are more, such as TimeOnIce, PenaltyKill, etc.

**Comment by andrewderango** [comment]
FYI it looks like the NHL messed up the `timeOnIcePerGame` field and shows TOI rather than ATOI, so you can use that.

![Screenshot 2024-09-05 at 10 29 31 PM](https://github.com/user-attachments/assets/712666a3-2dcf-42f1-bd51-288f22ec3fba)

**Comment by MunAli-Man** [comment]
This is very useful.  
Where can I see any details on the querying?  I want to find all possible query commands.  

How can I build a query that does this?
1. For gameId=2023020934, the faceoffpercentages for all players in the game
2. For Playerid=xxx, and gameId=2023020934, the faceoffpercentage for this 1 specific player.
3. For playerid=xxx, faceoffpercentage for all games this season, by game.

**Comment by MunAli-Man** [comment]
I was able to determine #1: [allfaceoffs for game 2023020801](https://api.nhle.com/stats/rest/en/skater/faceoffwins?isAggregate=false&isGame=true&sort=%5B%7B%22property%22:%22totalFaceoffWins%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22faceoffWinPct%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22playerId%22,%22direction%22:%22ASC%22%7D%5D&start=0&limit=9999&cayenneExp=gameTypeId=2%20and%20seasonId=20232024%20and%20gameId=2023020801)

**Comment by andrewderango** [comment]
https://api.nhle.com/stats/rest/en/skater/realtime?isAggregate=false&isGame=false&sort=%5B%7B%22property%22:%22hits%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22playerId%22,%22direction%22:%22ASC%22%7D%5D&start=0&limit=999&cayenneExp=gameTypeId=2%20and%20seasonId%3C=20232024%20and%20seasonId%3E=20232024

Contains hits and hits/60
