### ISSUE TITLE
Game Summary

### ISSUE THREAD

**Issue by martygriffin** [Zmalski/NHL-API-Reference#40]
Last year I was able to get a summary to team stats for a game via the boxscore api, has anyone figured out where that is now?

**Comment by ericdaoust1986** [comment]
https://api-web.nhle.com/v1/gamecenter/2024010039/right-rail

**Comment by martygriffin** [comment]
I found what I was looking for: https://api-web.nhle.com/v1/wsc/game-story/{game id}
